--- #YAML:1.0
name: Test-Expect
version: 0.30
author:
  - Leon Brocard, C<< <acme@astray.com> >>
abstract: Automated driving and testing of terminal-based programs
license: perl
generated_by: Module::Build version 0.2611, without YAML.pm
