--- #YAML:1.0
name: Test-Expect
version: 0.29
author:
  - Leon Brocard, C<< <acme@astray.com> >>
abstract: |-
  Automated driving and testing of terminal-based programs
license: perl
requires:
  Class::Accessor::Chained::Fast: 0
  Expect::Simple: 0
  Term::ReadLine: 0
  Test::Builder: 0
  Test::More: 0
provides:
  Test::Expect:
    file: lib/Test/Expect.pm
    version: 0.29
generated_by: Module::Build version 0.2605
